name: Deploy VitePress to GitHub Pages
on:
  push:
    branches: [master] # 触发条件，当推送到docs分支时
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master # 检查docs分支的代码
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 设置Node.js版本
      - name: Install pnpm
        run: npm install -g pnpm # 安装项目依赖
      - name: Install dependencies
        run: pnpm install # 安装项目依赖
      - name: Build VitePress site
        run: pnpm run docs:build # 构建静态网站
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # 使用GitHub Pages部署动作
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub提供的令牌进行身份验证
          publish_dir: .vitepress/dist # 指定要部署的目录，即VitePress构建的静态文件目录
