name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - master # 只有在master分支有推送时才会触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 获取全部提交历史，以便能正确生成git log
          submodules: true # 检出子模块

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # 或者你希望使用的其他版本

      - name: Install dependencies and build VitePress site
        run: |
          npm install -g pnpm
          pnpm install # 安装项目依赖  
          pnpm run docs:build # 构建VitePress文档站点，这取决于你的package.json中的scripts配置

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist # VitePress生成的静态文件目录，根据实际情况修改
          commit_message: 'Deploy VitePress site to GitHub Pages'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
